spring.application.name=clinic-appointment-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_db
spring.datasource.username=clinic_user
spring.datasource.password=clinic_password

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true

spring.application.name=clinic-appointment-manager

evolution.api.base-url=${EVOLUTION_API_BASE_URL:http://localhost:8081}
evolution.api.api-key=${EVOLUTION_API_KEY}
evolution.api.instance-name=${EVOLUTION_INSTANCE_NAME:clinic-instance}
